VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IDisconnect"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'概要:
'   Disconnectクラスが実装するインターフェイス
'
'目的:
'   Disconnectクラスが持つパラメータの初期化を行う
'
'作成者:
'   0145206097
'
Option Explicit

Public Sub Initialize(ByVal measSite As Long, ByVal setContainer As CContainer, ByVal reader As IParameterReader)
End Sub
