VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IEeeAuto_TestConditionChecker"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Option Explicit

Public Sub CheckBeforeCondition()
End Sub

Public Function CheckAfterCondition() As Boolean

End Function

Public Sub SetOperationMode(ByVal strMode As String)

End Sub

Public Sub SetEndPosition(ByVal strPos As String)

End Sub
