VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IImSceExperimentContent"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit


Public Property Get Children() As Collection

End Property

Public Property Get hasChild() As Boolean

End Property

Public Property Get Name() As String

End Property

Public Property Get Row() As Long

End Property
