VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ILimitTypeOperator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'概要:
'   各LimitTypeOperatorが実装するインターフェイス
'
'目的:
'   必要となるLimitTypeOperatorが実装する
'
'作成者:
'   0145184306
'
Option Explicit

Public Function Include(ByVal pLevel As Long) As Long

End Function
