VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IMacroController"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'概要:
'   マクロ実行機能提供用I/F
'
'目的:
'   マクロ有効無効切り替え対応
'

Option Explicit

Public Sub RunMacro(ByRef pParameters As CSetFunctionInfo)
'内容:
'   マクロを実行する
'
'パラメータ:
'   [pParameters]  In  CSetFunctionInfo型:  マクロ実行時に使用するパラメータ
'
'戻り値:
'
'注意事項:
'

End Sub
