VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IProcParamReplaceable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'概要:
'   各パラメータが実装するクラス
'
'目的:
'   各目的ごとに必要となるパラメータが実装する
'
'作成者:
'   0145184306
'
Option Explicit

Public Sub GetContents(ByVal pRoot As String, ByRef pRes As Collection)

End Sub

Public Sub ReplaceContent(ByVal pRoot As String, ByRef pParamContents As CImpLocalParamsContent)

End Sub

