VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISetCondition"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'概要:
'   Conditionパラメタの動的条件設定と静的条件設定の切り替えを行うインターフェイス
'
'目的:
'   マクロ実行方法の制御を行う
'
'作成者:
'   0145184935 K.Hara
'

Option Explicit

Public Sub Execute(ByVal FunctionInfo As CAcquireFunctionInfo)
End Sub
