VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IUserMacroAction"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function Execute() As Integer
End Function

Public Function GetUserMacroName() As String
End Function

Public Property Let SetUserMacroName(ByVal strName As String)
End Property

Public Sub Initialize()
End Sub

